"""
Django settings for digitalorganic project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(PROJECT_ROOT)

#root of project
#
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4(q)0n86*%+(mnh_h^d8#i&9h+j1&quy*&9jr1a*5hk$hof)xf'

AWS_STORAGE_BUCKET_NAME = 'napuor'
AWS_ACCESS_KEY_ID = 'AKIAJDZVRS54F6NUHFFA'
AWS_SECRET_ACCESS_KEY = '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'

AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'napuor@gmail.com'
EMAIL_HOST_PASSWORD = 'omshanti@123'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Application definition

INSTALLED_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sites',
	'corsheaders',
	'django_filters',
	'storages',
	'digitalorganic',
	'rest_framework',
	'rest_framework.authtoken',
	'allauth',
	'allauth.account',
	'product',
	'customers',
	'cart',
	'business',
	'import_export',
	'crispy_forms',
	'simplejson',
	)

#AUTH_USER_MODEL = 'customers.Account'

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
	'digitalorganic.middleware.TimezoneMiddleware'
)

AUTHENTICATION_BACKENDS = (
	# Needed to login by username in Django admin, regardless of `allauth`
	"django.contrib.auth.backends.ModelBackend",
	# `allauth` specific authentication methods, such as login by e-mail
 )

ROOT_URLCONF = 'digitalorganic.urls'
SITE_ID = 1
TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, "templates")],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]


'''
	,'DEFAULT_RENDERER_CLASSES': (
		'rest_framework.renderers.JSONRenderer',
	)
'''


REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'rest_framework.authentication.BasicAuthentication',
		#'rest_framework.authentication.SessionAuthentication',
		'rest_framework.authentication.TokenAuthentication',
	)
   }
WSGI_APPLICATION = 'digitalorganic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}

ALLOWED_HOSTS= ['localhost', '127.0.0.1', '[::1]']
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED=True
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True
TIME_ZONE =  'Asia/Kolkata'
USE_TZ = False

OLD_PASSWORD_FIELD_ENABLED = True

LOGOUT_ON_PASSWORD_CHANGE = True

#REST_USE_JWT = True
SERVE_MEDIA = True

	
STATIC_ROOT = os.path.join(PROJECT_ROOT, "static")

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)


MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
#MEDIA_ROOT = os.path.join(PROJECT_ROOT, "media")
MEDIA_ROOT = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
#MEDIA_URL = '/media/'
#MEDIA_URL = "https://%s/media" % AWS_S3_CUSTOM_DOMAIN

#MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "media_root")
#MEDIA_ROOT = os.path.join(PROJECT_ROOT, "media")

#Crispy FORM TAGs SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap3'


